version: "3"

services:
  main:
    build:
      args:
        PROJECT_ARTIFACT_ID: ${PROJECT_ARTIFACT_ID:-group-3}
        PROJECT_VERSION: ${PROJECT_VERSION:-0.1-0}
    image: sem-team-project-image:latest
    container_name: sem-team-project-container

  db:
    build: vendor/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always