version: "3"

services:
  main:
    build:
      args:
        PROJECT_ARTIFACT_ID: ${PROJECT_ARTIFACT_ID}
        PROJECT_VERSION: ${PROJECT_VERSION}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-default}
    image: sem-team-project-app:latest
    container_name: App
    environment:
      MYSQL_HOST: "db"
    depends_on:
      - db

  db:
    build:
      context: db/.
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-default}
    command: --default-authentication-plugin=mysql_native_password --skip-name-resolve
    restart: on-failure
    image: sem-team-project-db:latest
    container_name: DB