name: Build and Test Docker Image
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # - name: Setup network
      #   run: |
      #     docker network create --driver bridge se-methods
      #     docker pull mongo
      #     docker run -d --name mongo-dbserver --network se-methods mongo
      - name: Unit Tests
        run: mvn test -DfailIfNoTests=false
      - name: Build
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: JARs
          path: |
            target/*.jar
      - name: Run image
        run: ./start.sh
      - name: view logs
        run: docker logs sem-team-project-container