#file: noinspection SpellCheckingInspection,SpellCheckingInspection
name: Build and Test Docker Image
on: push

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest='!*IntegrationTest' test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker compose -f ./docker-compose.yml -f ./docker-compose.dev.linux.yml up db -d
          mvn -Dtest='!*UnitTest' test
      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/site/jacoco
          flags: Integration Tests
          verbose: false
          slug: 2004seraph/SET08103

  build:
    name: Build and Run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: ./scripts/build.sh
      - name: Run image
        run: ./scripts/start.sh
#      - name: view logs
#        run: docker logs sem-team-project-app